// ** LOCALHOST **
GET http://localhost:8080/

### GET ALL PROJECTS
GET http://localhost:8080/projects

### GET PROJECT BY ID
GET http://localhost:8080/projects/63c6d010d1398e8d34f449aa

### CREATE PROJECT
POST http://localhost:8080/projects/
content-type: application/json

{
    "title": "test",
    "websiteUrl": "test",
    "gitHubUrl": "test",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "test",
    "imgUrl_lg": "test",
    "imgAlt": "test"
}


# ### UPDATE PROJECT
# PUT http://localhost:8080/projects/63b87d672b58c8e87964ad30 
# content-type: application/json

# {
#     "title": "test1",
#     "websiteUrl": "test",
#     "gitHubUrl": "test",
#     "techStack": "test",
#     "summary": "test",
#     "imgUrl_sm": "test",
#     "imgUrl_lg": "test",
#     "imgAlt": "test"
# }

# ### DELETE PROJECT
# DELETE http://localhost:8080/projects/63bdea039668f9228517a154


# // ** PRODUCTION DEPLOY **

# ### GET ALL PROJECTS
# GET https://shaira341-w01-personal-assignment.onrender.com/projects

# ### GET PROJECT BY ID
# GET https://shaira341-w01-personal-assignment.onrender.com/projects/63b87d672b58c8e87964ad2f

# ### CREATE PROJECT
# POST https://shaira341-w01-personal-assignment.onrender.com/projects
# content-type: application/json

# {
#     "title": "test",
#     "websiteUrl": "test",
#     "gitHubUrl": "test",
#     "techStack": "test",
#     "summary": "test",
#     "imgUrl_sm": "test",
#     "imgUrl_lg": "test",
#     "imgAlt": "test"
# }

# ### UPDATE PROJECT
# PUT https://shaira341-w01-personal-assignment.onrender.com/projects/63b87d672b58c8e87964ad30 
# content-type: application/json

# {
#     "firstName":"Sarah",
#     "lastName":"Echmo",
#     "email":"test@gmail.com",
#     "favoriteColor":"Green",
#     "birthday":"12/12/1995"
# }

# ### DELETE PROJECT
# DELETE https://shaira341-w01-personal-assignment.onrender.com/projects/63c08a0ccec8e3bf4d7d3a47