// ** LOCALHOST 
GET http://localhost:8080/

//** COURSES
### GET ALL COURSES
GET http://localhost:8080/courses

### GET COURSE BY ID
GET http://localhost:8080/courses/63c6d01cd1398e8d34f449b3

//** PROJECTS
### GET ALL PROJECTS
GET http://localhost:8080/projects

### GET PROJECT BY ID
GET http://localhost:8080/projects/63c6d010d1398e8d34f449a6

### CREATE PROJECT
POST http://localhost:8080/projects/
content-type: application/json

{
    "title": "test",
    "websiteUrl": "http://www.website.com",
    "gitHubUrl": "http://www.github.com",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "sdfpng",
    "imgUrl_lg": "dad",
    "imgAlt": "test"
}


### UPDATE PROJECT
PUT http://localhost:8080/projects/63cbd46b33e9e7355471d2f1
content-type: application/json

{
    "title": "Project Names",
    "websiteUrl": "http://www.website.com",
    "gitHubUrl": "http://www.github.com",
    "techStack": "HTML, CSS, JS",
    "summary": "This is a summary",
    "imgUrl_sm": "images/placeholder_sm.jpg",
    "imgUrl_lg": "images/placeholder_lg.jpg",
    "imgAlt": "Project"
}


### DELETE PROJECT
DELETE http://localhost:8080/projects/63cbd46b33e9e7355471d2f1


# // ** PRODUCTION DEPLOY **

//** COURSES
### GET ALL COURSES
GET https://portfolio-app-iu9g.onrender.com/courses

### GET COURSE BY ID
GET https://portfolio-app-iu9g.onrender.com/courses/63c6d01cd1398e8d34f449ad

//** PROJECTS
### GET ALL PROJECTS
GET https://portfolio-app-iu9g.onrender.com/projects

### GET PROJECT BY ID
GET https://portfolio-app-iu9g.onrender.com/projects/63cb0e08575f6f39a0a2cece

### CREATE PROJECT
POST https://portfolio-app-iu9g.onrender.com/projects
content-type: application/json

{
    "title": "test2",
    "websiteUrl": "http://www.website.com",
    "gitHubUrl": "http://www.github.com",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "test",
    "imgUrl_lg": "test",
    "imgAlt": "test"
}

### UPDATE PROJECT
PUT https://portfolio-app-iu9g.onrender.com/projects/63cb0e08575f6f39a0a2cece
content-type: application/json

{
    "title": "Project Name",
    "websiteUrl": "http://www.website.com",
    "gitHubUrl": "http://www.github.com",
    "techStack": "HTML, CSS, JS",
    "summary": "This is a summary",
    "imgUrl_sm": "images/placeholder_sm.jpg",
    "imgUrl_lg": "images/placeholder_lg.jpg",
    "imgAlt": "Project"
}


### DELETE PROJECT
DELETE https://portfolio-app-iu9g.onrender.com/projects/63c9a38a2f489ecfd035ba94