// ** LOCALHOST 
GET http://localhost:8080/

//** COURSES
### GET ALL COURSES
GET http://localhost:8080/courses

### GET COURSE BY ID
GET http://localhost:8080/courses/63c6d01cd1398e8d34f449b3

//** PROJECTS
### GET ALL PROJECTS
GET http://localhost:8080/projects

### GET PROJECT BY ID
GET http://localhost:8080/projects/63c6d010d1398e8d34f449aa

### CREATE PROJECT
POST http://localhost:8080/projects/
content-type: application/json

{
    "title": "test",
    "websiteUrl": "test",
    "gitHubUrl": "test",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "test",
    "imgUrl_lg": "test",
    "imgAlt": "test"
}


### UPDATE PROJECT
PUT http://localhost:8080/projects/63c9a38a2f489ecfd035ba94
content-type: application/json

{
    "title": "Testing",
    "websiteUrl": "test",
    "gitHubUrl": "test",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "test",
    "imgUrl_lg": "test",
    "imgAlt": "test"
}

### DELETE PROJECT
DELETE http://localhost:8080/projects/63c74e87e3fff21ba0103305


# // ** PRODUCTION DEPLOY **

//** COURSES
### GET ALL COURSES
GET https://portfolio-app-iu9g.onrender.com/courses

### GET COURSE BY ID
GET https://portfolio-app-iu9g.onrender.com/courses/63c6d01cd1398e8d34f449ad

//** PROJECTS
### GET ALL PROJECTS
GET https://portfolio-app-iu9g.onrender.com/projects

### GET PROJECT BY ID
GET https://portfolio-app-iu9g.onrender.com/projects/63c6d010d1398e8d34f449aa

### CREATE PROJECT
POST https://portfolio-app-iu9g.onrender.com/projects
content-type: application/json

{
    "title": "test2",
    "websiteUrl": "test",
    "gitHubUrl": "test",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "test",
    "imgUrl_lg": "test",
    "imgAlt": "test"
}

### UPDATE PROJECT
PUT https://portfolio-app-iu9g.onrender.com/projects/63c9a38a2f489ecfd035ba94

{
    "title": "test2",
    "websiteUrl": "test",
    "gitHubUrl": "test",
    "techStack": "test",
    "summary": "test",
    "imgUrl_sm": "test",
    "imgUrl_lg": "test",
    "imgAlt": "test"
}

### DELETE PROJECT
DELETE ttps://portfolio-app-iu9g.onrender.com/projects/63c08a0ccec8e3bf4d7d3a47