GET http://localhost:8080/

### GET ALL CONTACTS
GET http://localhost:8080/contacts 

### GET CONTACT BY ID
GET http://localhost:8080/contacts/63b87d672b58c8e87964ad2f

### CREATE CONTACT
POST http://localhost:8080/contacts/
content-type: application/json

{
    "firstName": "Greg",
    "lastName": "Kherby",
    "email": "gk@gmail.com",
    "favoriteColor": "green",
    "birthday": "09/09/2003"
}

###
PUT http://localhost:8080/contacts/63b87d672b58c8e87964ad30 
content-type: application/json

{
    "firstName":"Sara",
    "lastName":"Echmo",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/12/1995"
}

### DELETE contact
DELETE http://localhost:8080/contacts/63bd9d7f41ab659108c94725
