// ** LOCALHOST **
GET http://localhost:8080/

### GET ALL CONTACTS
GET http://localhost:8080/contacts 

### GET CONTACT BY ID
GET http://localhost:8080/contacts/63b87d672b58c8e87964ad2f

### CREATE CONTACT
POST http://localhost:8080/contacts/
content-type: application/json

{
    "firstName": "Greg",
    "lastName": "Kherby",
    "email": "gk@gmail.com",
    "favoriteColor": "green",
    "birthday": "09/09/2003"
}


### UPDATE CONTACT
PUT http://localhost:8080/contacts/63b87d672b58c8e87964ad30 
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Echmo",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/12/1995"
}

### DELETE CONTACT
DELETE http://localhost:8080/contacts/63bdea039668f9228517a154


// ** PRODUCTION DEPLOY **

### GET ALL CONTACTS
GET https://shaira341-w01-personal-assignment.onrender.com/contacts

### GET CONTACT BY ID
GET https://shaira341-w01-personal-assignment.onrender.com/contacts/63b87d672b58c8e87964ad2f

### CREATE CONTACT
POST https://shaira341-w01-personal-assignment.onrender.com/contacts
content-type: application/json

{
    "firstName": "Greg",
    "lastName": "Kherby",
    "email": "gk@gmail.com",
    "favoriteColor": "green",
    "birthday": "09/09/2003"
}

### UPDATE CONTACT
PUT https://shaira341-w01-personal-assignment.onrender.com/contacts/63b87d672b58c8e87964ad30 
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Echmo",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/12/1995"
}

### DELETE CONTACT
DELETE https://shaira341-w01-personal-assignment.onrender.com/contacts/63c08a0ccec8e3bf4d7d3a47